from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: KC4.0_Data_Tools
    Package: TestProject.Generated.Tests.KC40DataTools
    Test: 9_AutomationTestEdit
    Generated by: Trần Linh (linhya21@gmail.com)
    Generated on 04/20/2022, 09:09:20
"""


@pytest.fixture()
def driver():
    driver = webdriver.Firefox(token="GACZSbNIlK-5Ayy_12ybWwZEj4GhUCIrTzc_9RjbaF0",
                               project_name="KC4.0_Data_Tools",
                               job_name="9_AutomationTestEdit")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:3005/document"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Scroll window by ('0','366')
    driver.execute_script("window.scrollBy(0,366)")

    # 3. Click 'Hiển thị đầy đủ'
    hi_n_th_y_ = driver.find_element(By.XPATH,
                                     "//tr[2]//span[. = 'Hiển thị đầy đủ']")
    hi_n_th_y_.click()

    # 4. Click 'Đóng'
    _ng = driver.find_element(By.XPATH,
                              "//span[. = 'Đóng']")
    _ng.click()

    # 5. Scroll window by ('0','-366')
    driver.execute_script("window.scrollBy(0,-366)")

    # 6. Click 'Tìm kiếm văn bản...'
    t_m_ki_m_v_n_b_n_ = driver.find_element(By.XPATH,
                                            "//input[@placeholder = 'Tìm kiếm văn bản...']")
    t_m_ki_m_v_n_b_n_.click()

    # 7. Type 'Those' in 'Tìm kiếm văn bản...'
    t_m_ki_m_v_n_b_n_ = driver.find_element(By.XPATH,
                                            "//input[@placeholder = 'Tìm kiếm văn bản...']")
    t_m_ki_m_v_n_b_n_.send_keys("Those")

    # 8. Click 'Tìm kiếm'
    t_m_ki_m = driver.find_element(By.XPATH,
                                   "//span[. = 'Tìm kiếm']")
    t_m_ki_m.click()

    # 9. Scroll window by ('0','313')
    driver.execute_script("window.scrollBy(0,313)")

    # 10. Scroll window by ('0','-313')
    driver.execute_script("window.scrollBy(0,-313)")

    # 11. Click 'Tìm kiếm văn bản...'
    t_m_ki_m_v_n_b_n_ = driver.find_element(By.XPATH,
                                            "//input[@placeholder = 'Tìm kiếm văn bản...']")
    t_m_ki_m_v_n_b_n_.click()

    # 12. Click 'Tìm kiếm văn bản...'
    t_m_ki_m_v_n_b_n_ = driver.find_element(By.XPATH,
                                            "//input[@placeholder = 'Tìm kiếm văn bản...']")
    t_m_ki_m_v_n_b_n_.click()

    # 13. Click 'Chưa đánh giá'
    ch_a_nh_gi_ = driver.find_element(By.XPATH,
                                      "//span[. = 'Chưa đánh giá']")
    ch_a_nh_gi_.click()

    # 14. Click 'Tốt'
    t_t = driver.find_element(By.XPATH,
                              "//div[2]/div[. = 'Tốt']")
    t_t.click()

    # 15. Click 'Tìm kiếm'
    t_m_ki_m = driver.find_element(By.XPATH,
                                   "//span[. = 'Tìm kiếm']")
    t_m_ki_m.click()

    # 16. Scroll window by ('0','260')
    driver.execute_script("window.scrollBy(0,260)")

    # 17. Scroll window by ('0','-260')
    driver.execute_script("window.scrollBy(0,-260)")

    # 18. Click 'DIV1'
    div1 = driver.find_element(By.XPATH,
                               "//div[2]/div[1]/div[2]/div/div")
    div1.click()

    # 19. Click 'Tiếng Khmer'
    ti_ng_khmer = driver.find_element(By.XPATH,
                                      "//div[3]/div[. = 'Tiếng Khmer']")
    ti_ng_khmer.click()

    # 20. Click 'Tốt1'
    t_t1 = driver.find_element(By.XPATH,
                               "//span[. = 'Tốt']")
    t_t1.click()

    # 21. Click 'Tất cả4'
    t_t_c_4 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div/div/div[2]/div[1]/div/div/div/div[. = 'Tất cả']")
    t_t_c_4.click()

    # 22. Click 'Tìm kiếm'
    t_m_ki_m = driver.find_element(By.XPATH,
                                   "//span[. = 'Tìm kiếm']")
    t_m_ki_m.click()

    # 23. Scroll window by ('0','568')
    driver.execute_script("window.scrollBy(0,568)")

    # 24. Scroll window by ('0','-311')
    driver.execute_script("window.scrollBy(0,-311)")

    # 25. Scroll window by ('0','-24')
    driver.execute_script("window.scrollBy(0,-24)")

    # 26. Scroll window by ('0','-132')
    driver.execute_script("window.scrollBy(0,-132)")

    # 27. Click 'Tải lên2'
    t_i_l_n2 = driver.find_element(By.XPATH,
                                   "//button[. = 'Tải lên']")
    t_i_l_n2.click()

    # 28. Click 'LABEL1'
    label1 = driver.find_element(By.XPATH,
                                 "//div[1]/div[1]/div/label")
    label1.click()

    # 29. Type 'TestVN1.txt' in '1'
    _1 = driver.find_element(By.CSS_SELECTOR,
                             "[id = '1']")
    _1.send_keys("TestVN1.txt")

    # 30. Click 'svg4'
    svg4 = driver.find_element(By.XPATH,
                               "//div[2]/div[1]/div[2]/label/*")
    svg4.click()

    # 31. Type 'TestLao1.txt' in '2'
    _2 = driver.find_element(By.CSS_SELECTOR,
                             "[id = '2']")
    _2.send_keys("TestLao1.txt")

    # 32. Click 'Tải lên1'
    t_i_l_n1 = driver.find_element(By.XPATH,
                                   "//button[2]/span[. = 'Tải lên']")
    t_i_l_n1.click()

    # 33. Click 'SPAN3'
    span3 = driver.find_element(By.XPATH,
                                "//div[4]/div/div[2]/div/div[2]/button/span")
    span3.click()

    # 34. Click 'Tiếng Khmer1'
    ti_ng_khmer1 = driver.find_element(By.XPATH,
                                       "//span[. = 'Tiếng Khmer']")
    ti_ng_khmer1.click()

    # 35. Click 'Tất cả3'
    t_t_c_3 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div/div/div[2]/div[1]/div/div/div/div[. = 'Tất cả']")
    t_t_c_3.click()

    # 36. Click 'SPAN4'
    span4 = driver.find_element(By.XPATH,
                                "//div[2]/div[1]/span/span")
    span4.click()

    # 37. Click 'user_99'
    user_99 = driver.find_element(By.XPATH,
                                  "//div[. = 'user_99']")
    user_99.click()

    # 38. Scroll window by ('0','545')
    driver.execute_script("window.scrollBy(0,545)")

    # 39. Scroll window by ('0','-203')
    driver.execute_script("window.scrollBy(0,-203)")

    # 40. Scroll window by ('0','-93')
    driver.execute_script("window.scrollBy(0,-93)")

    # 41. Scroll window by ('0','-350')
    driver.execute_script("window.scrollBy(0,-350)")
