"""empty message

Revision ID: 603ec7635a3b
Revises: 23bfd3f498d5
Create Date: 2020-11-12 23:32:21.969203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '603ec7635a3b'
down_revision = '23bfd3f498d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_content', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_content', sa.Column('content', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
