"""empty message

Revision ID: 33a7f303b61a
Revises: c7bbe986ebc2
Create Date: 2020-12-01 00:00:11.256197

"""

# revision identifiers, used by Alembic.
revision = '33a7f303b61a'
down_revision = 'c7bbe986ebc2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('camera_behind_amount', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('camera_behind_feature', sa.String(length=160), nullable=True))
    op.add_column('product', sa.Column('camera_behind_pixel', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('camera_selfie', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('os_name', sa.String(length=80), nullable=True))
    op.add_column('product', sa.Column('os_version', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('ram', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('resolution', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('rom', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('screen_size', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('screen_tech', sa.String(length=80), nullable=True))
    op.create_unique_constraint(op.f('uq_product_id'), 'product', ['id'])
    op.create_unique_constraint(op.f('uq_supplier_id'), 'supplier', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_supplier_id'), 'supplier', type_='unique')
    op.drop_constraint(op.f('uq_product_id'), 'product', type_='unique')
    op.drop_column('product', 'screen_tech')
    op.drop_column('product', 'screen_size')
    op.drop_column('product', 'rom')
    op.drop_column('product', 'resolution')
    op.drop_column('product', 'ram')
    op.drop_column('product', 'price')
    op.drop_column('product', 'os_version')
    op.drop_column('product', 'os_name')
    op.drop_column('product', 'camera_selfie')
    op.drop_column('product', 'camera_behind_pixel')
    op.drop_column('product', 'camera_behind_feature')
    op.drop_column('product', 'camera_behind_amount')
    # ### end Alembic commands ###
