"""empty message

Revision ID: 69886c8e4ee0
Revises: 0f4d314361a2
Create Date: 2020-12-12 10:57:35.138250

"""

# revision identifiers, used by Alembic.
revision = '69886c8e4ee0'
down_revision = '0f4d314361a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_supply_product_pid', 'supply_product', type_='unique')
    op.drop_constraint('uq_supply_product_sid', 'supply_product', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_supply_product_sid', 'supply_product', ['sid'])
    op.create_unique_constraint('uq_supply_product_pid', 'supply_product', ['pid'])
    # ### end Alembic commands ###
