"""empty message

Revision ID: c7bbe986ebc2
Revises: 8b356e171c40
Create Date: 2020-11-30 00:04:03.684317

"""

# revision identifiers, used by Alembic.
revision = 'c7bbe986ebc2'
down_revision = '8b356e171c40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('id', name=op.f('uq_product_id'))
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier')),
    sa.UniqueConstraint('id', name=op.f('uq_supplier_id'))
    )
    op.create_table('supply_product',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['product.id'], name=op.f('fk_supply_product_pid_product')),
    sa.ForeignKeyConstraint(['sid'], ['supplier.id'], name=op.f('fk_supply_product_sid_supplier')),
    sa.PrimaryKeyConstraint('sid', 'pid', name=op.f('pk_supply_product')),
    sa.UniqueConstraint('pid', name=op.f('uq_supply_product_pid')),
    sa.UniqueConstraint('sid', name=op.f('uq_supply_product_sid'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supply_product')
    op.drop_table('supplier')
    op.drop_table('product')
    # ### end Alembic commands ###
