"""empty message

Revision ID: 01b8b5d3f83f
Revises: 2109f673a9da
Create Date: 2020-11-09 22:55:03.200729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01b8b5d3f83f'
down_revision = '2109f673a9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_content', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user_content', 'new_content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('user_content', 'original_content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('user_content', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_content', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user_content', 'original_content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('user_content', 'new_content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('user_content', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
