"""empty message

Revision ID: 23bfd3f498d5
Revises: 98af07975445
Create Date: 2020-11-12 23:27:55.363340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23bfd3f498d5'
down_revision = '98af07975445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_content', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('user_content', 'new_content')
    op.drop_column('user_content', 'input_attrs')
    op.drop_column('user_content', 'original_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_content', sa.Column('original_content', mysql.TEXT(), nullable=False))
    op.add_column('user_content', sa.Column('input_attrs', mysql.TEXT(), nullable=False))
    op.add_column('user_content', sa.Column('new_content', mysql.TEXT(), nullable=False))
    op.drop_column('user_content', 'content')
    # ### end Alembic commands ###
