"""empty message

Revision ID: a957a6e54058
Revises: a9ea873590ef
Create Date: 2020-11-21 15:13:24.325718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a957a6e54058'
down_revision = 'a9ea873590ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_content', sa.Column('model_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_content', 'model_name')
    # ### end Alembic commands ###
